import { Test, Booking, User } from './types';

// Sample tests data - this acts as seed data / demo data
// In production, this comes from Firestore
export const sampleTests: Test[] = [
  {
    id: 'fit-india-essential',
    name: 'Fit India Full Body Checkup - Essential',
    price: 1499,
    originalPrice: 7138,
    discount: 79,
    category: 'Full Body',
    parameters: ['Vitamin D', 'Heart', 'Diabetes (HbA1c)', 'Liver', 'Kidney', 'Sugar', 'CBC', 'Thyroid'],
    description: 'A comprehensive full body checkup covering 94 vital parameters including heart, liver, kidney function, diabetes screening, and vitamin levels. Ideal for preventive health monitoring.',
    reportTime: 14,
    isPackage: true,
    includedTests: ['CBC', 'Lipid Profile', 'Liver Function', 'Kidney Function', 'Thyroid Profile', 'HbA1c', 'Vitamin D', 'Iron Studies'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 94,
    preparations: ['12 hours fasting required', 'Avoid alcohol 24 hours before test', 'Drink plenty of water'],
  },
  {
    id: 'smart-full-body',
    name: 'Smart Full Body Checkup',
    price: 997,
    originalPrice: 2749,
    discount: 64,
    category: 'Full Body',
    parameters: ['Diabetes (HbA1c)', 'Sugar', 'Lipid', 'Liver', 'Kidney', 'Infection'],
    description: 'An intelligent full body checkup with 89 parameters covering essential health markers. Get doctor-verified smart reports with actionable insights.',
    reportTime: 14,
    isPackage: true,
    includedTests: ['CBC', 'Lipid Profile', 'Sugar', 'Liver Function', 'Kidney Function', 'Infection Markers'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 89,
    preparations: ['10-12 hours fasting required', 'Morning sample preferred'],
  },
  {
    id: 'annual-advance',
    name: 'Annual Full Body Checkup - Advance',
    price: 1799,
    originalPrice: 8566,
    discount: 79,
    category: 'Full Body',
    parameters: ['Iron Deficiency', 'Heart', 'Diabetes (HbA1c)', 'Sugar', 'Thyroid', 'Vitamin D', 'B12'],
    description: 'The most comprehensive annual checkup with 96 parameters. Covers advanced cardiac markers, complete metabolic panel, and cancer screening markers.',
    reportTime: 14,
    isPackage: true,
    includedTests: ['CBC', 'Lipid Profile', 'LFT', 'KFT', 'Thyroid', 'HbA1c', 'Vitamin D', 'B12', 'Iron', 'Cardiac Markers'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 96,
    preparations: ['12 hours fasting required', 'Avoid heavy meals the night before'],
  },
  {
    id: 'hba1c-test',
    name: 'HBA1C Test',
    price: 349,
    originalPrice: 587,
    discount: 41,
    category: 'Diabetes',
    parameters: ['HbA1c'],
    description: 'A single blood test that shows your average blood sugar levels over the past 2-3 months. Essential for diabetes monitoring and management.',
    reportTime: 13,
    isPackage: false,
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 2,
    preparations: ['No fasting required'],
  },
  {
    id: 'cbc-test',
    name: 'Complete Blood Count (CBC) Test',
    price: 299,
    originalPrice: 525,
    discount: 43,
    category: 'Full Body',
    parameters: ['RBC', 'WBC', 'Hemoglobin', 'Platelets', 'Hematocrit', 'MCV', 'MCH', 'MCHC'],
    description: 'A Complete Blood Count (CBC) test measures key components of your blood. It helps diagnose conditions like anemia, infections, blood cancers, and clotting disorders.',
    reportTime: 11,
    isPackage: false,
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 26,
    preparations: ['No special preparation needed'],
  },
  {
    id: 'thyroid-profile',
    name: 'Thyroid Profile Total',
    price: 429,
    originalPrice: 980,
    discount: 56,
    category: 'Thyroid',
    parameters: ['T3', 'T4', 'TSH'],
    description: 'A comprehensive thyroid panel measuring total T3, total T4, and TSH to monitor thyroid function. Helps detect hyperthyroidism and hypothyroidism.',
    reportTime: 14,
    isPackage: false,
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 3,
    preparations: ['No fasting required', 'Early morning sample preferred'],
  },
  {
    id: 'blood-sugar-fasting',
    name: 'Blood Sugar Fasting',
    price: 69,
    originalPrice: 198,
    discount: 65,
    category: 'Diabetes',
    parameters: ['Fasting Glucose'],
    description: 'Fasting blood sugar test to measure glucose levels, detect early signs of diabetes and monitor blood sugar control.',
    reportTime: 12,
    isPackage: false,
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 1,
    preparations: ['10-12 hours fasting required', 'Water intake is allowed'],
  },
  {
    id: 'lipid-profile',
    name: 'Lipid Profile Test',
    price: 399,
    originalPrice: 750,
    discount: 47,
    category: 'Heart',
    parameters: ['Total Cholesterol', 'HDL', 'LDL', 'VLDL', 'Triglycerides', 'Cholesterol/HDL Ratio'],
    description: 'Comprehensive lipid panel to assess cardiovascular risk. Measures total cholesterol, HDL (good), LDL (bad), and triglycerides.',
    reportTime: 12,
    isPackage: false,
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 6,
    preparations: ['10-12 hours fasting required'],
  },
  {
    id: 'vitamin-d-test',
    name: 'Vitamin D (25-OH) Test',
    price: 549,
    originalPrice: 1200,
    discount: 54,
    category: 'Vitamin',
    parameters: ['25-Hydroxy Vitamin D'],
    description: 'Measures the level of Vitamin D in your blood. Vitamin D is essential for bone health, immune function, and mood regulation.',
    reportTime: 14,
    isPackage: false,
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 1,
    preparations: ['No fasting required'],
  },
  {
    id: 'vitamin-b12-test',
    name: 'Vitamin B12 Test',
    price: 499,
    originalPrice: 1100,
    discount: 55,
    category: 'Vitamin',
    parameters: ['Vitamin B12 (Cyanocobalamin)'],
    description: 'Measures Vitamin B12 levels crucial for nerve function, red blood cell formation, and DNA synthesis. Deficiency can cause fatigue and neurological issues.',
    reportTime: 14,
    isPackage: false,
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 1,
    preparations: ['No fasting required'],
  },
  {
    id: 'liver-function',
    name: 'Liver Function Test (LFT)',
    price: 379,
    originalPrice: 820,
    discount: 54,
    category: 'Liver',
    parameters: ['SGOT', 'SGPT', 'ALP', 'Bilirubin Total', 'Bilirubin Direct', 'ALT', 'AST', 'GGT', 'Total Protein', 'Albumin'],
    description: 'A comprehensive liver function assessment measuring enzymes, proteins, and bilirubin to evaluate liver health and detect liver diseases.',
    reportTime: 13,
    isPackage: false,
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 12,
    preparations: ['10-12 hours fasting required'],
  },
  {
    id: 'kidney-function',
    name: 'Kidney Function Test (KFT)',
    price: 449,
    originalPrice: 900,
    discount: 50,
    category: 'Kidney',
    parameters: ['Creatinine', 'BUN', 'Uric Acid', 'Calcium', 'Phosphorus', 'Sodium', 'Potassium', 'Chloride'],
    description: 'Complete kidney function profile measuring creatinine, urea, electrolytes to assess kidney health and filtration capacity.',
    reportTime: 13,
    isPackage: false,
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 11,
    preparations: ['No special preparation needed'],
  },
  {
    id: 'fever-panel',
    name: 'Fever Panel Basic',
    price: 599,
    originalPrice: 1450,
    discount: 59,
    category: 'Fever',
    parameters: ['CBC', 'Widal', 'Malaria Antigen', 'Dengue NS1', 'CRP'],
    description: 'Essential fever panel to diagnose common causes of fever including typhoid, malaria, dengue, and bacterial infections.',
    reportTime: 14,
    isPackage: true,
    includedTests: ['CBC', 'Widal Test', 'Malaria Antigen', 'Dengue NS1 Antigen', 'CRP Quantitative'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 35,
    preparations: ['No fasting required'],
  },
  {
    id: 'heart-health-advance',
    name: 'Heart Health Checkup - Advanced',
    price: 1299,
    originalPrice: 4500,
    discount: 71,
    category: 'Heart',
    parameters: ['Lipid Profile', 'hs-CRP', 'Homocysteine', 'HbA1c', 'ECG Interpretation', 'Cardiac Risk Markers'],
    description: 'Advanced cardiac risk assessment with lipid profile, inflammatory markers, and specialized cardiac biomarkers. Ideal for those with family history of heart disease.',
    reportTime: 16,
    isPackage: true,
    includedTests: ['Lipid Profile', 'hs-CRP', 'Homocysteine', 'HbA1c', 'Apolipoprotein B', 'Lipoprotein(a)'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Noida', 'Gurgaon'],
    active: true,
    testsCount: 42,
    preparations: ['12 hours fasting required'],
  },
  {
    id: 'women-health-basic',
    name: 'Women Health Checkup - Basic',
    price: 1599,
    originalPrice: 5200,
    discount: 69,
    category: 'Women Health',
    parameters: ['CBC', 'Thyroid', 'Iron', 'Vitamin D', 'B12', 'Calcium', 'Hormones'],
    description: 'Specially designed health checkup for women covering essential parameters including hormonal balance, iron levels, thyroid, and bone health markers.',
    reportTime: 16,
    isPackage: true,
    includedTests: ['CBC', 'Thyroid Profile', 'Iron Studies', 'Vitamin D', 'B12', 'Calcium', 'FSH', 'LH', 'Prolactin'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 58,
    preparations: ['10-12 hours fasting required', 'Inform about menstrual cycle day'],
  },
  {
    id: 'immunity-package',
    name: 'Immunity Screening Package',
    price: 899,
    originalPrice: 2800,
    discount: 68,
    category: 'Immunity',
    parameters: ['CBC', 'CRP', 'Vitamin D', 'Zinc', 'Iron', 'Total IgE'],
    description: 'Comprehensive immunity assessment including vitamin levels, inflammatory markers, and immune function tests. Boost your immunity with data-driven insights.',
    reportTime: 14,
    isPackage: true,
    includedTests: ['CBC', 'CRP', 'Vitamin D', 'Zinc', 'Iron Profile', 'Total IgE', 'ESR'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Noida', 'Gurgaon'],
    active: true,
    testsCount: 45,
    preparations: ['No fasting required'],
  },
  {
    id: 'allergy-panel',
    name: 'Allergy Screening Panel',
    price: 2499,
    originalPrice: 6500,
    discount: 62,
    category: 'Allergy',
    parameters: ['Total IgE', 'Food Panel', 'Inhalant Panel', 'Pollen', 'Dust Mite', 'Pet Dander'],
    description: 'Comprehensive allergy testing covering food allergies, environmental allergens, and inhalant triggers. Identify your specific allergy triggers.',
    reportTime: 48,
    isPackage: true,
    includedTests: ['Total IgE', 'Food Allergy Panel (30)', 'Inhalant Allergy Panel (20)'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad'],
    active: true,
    testsCount: 52,
    preparations: ['No fasting required', 'Avoid antihistamines 3 days before test'],
  },
  {
    id: 'diabetes-screening',
    name: 'Diabetes Screening Package',
    price: 799,
    originalPrice: 2100,
    discount: 62,
    category: 'Diabetes',
    parameters: ['Fasting Sugar', 'PP Sugar', 'HbA1c', 'Insulin Fasting', 'Kidney Function'],
    description: 'Complete diabetes assessment with fasting and post-prandial sugar, HbA1c for long-term control, and kidney function to check for complications.',
    reportTime: 14,
    isPackage: true,
    includedTests: ['Fasting Blood Sugar', 'Post Prandial Sugar', 'HbA1c', 'Fasting Insulin', 'KFT', 'Urine Routine'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 28,
    preparations: ['12 hours fasting required', 'Second sample 2 hours after meal'],
  },
  {
    id: 'bone-health',
    name: 'Bone Health Profile',
    price: 1199,
    originalPrice: 3200,
    discount: 63,
    category: 'Bone',
    parameters: ['Calcium', 'Phosphorus', 'Vitamin D', 'Vitamin B12', 'ALP', 'PTH', 'Magnesium'],
    description: 'Comprehensive bone health assessment including calcium, Vitamin D, phosphorus, and parathyroid hormone. Essential for osteoporosis screening.',
    reportTime: 16,
    isPackage: true,
    includedTests: ['Calcium', 'Phosphorus', 'Vitamin D', 'B12', 'ALP', 'PTH', 'Magnesium', 'Uric Acid'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Noida', 'Gurgaon'],
    active: true,
    testsCount: 12,
    preparations: ['No fasting required'],
  },
  {
    id: 'infection-panel',
    name: 'Infection Screening Panel',
    price: 1099,
    originalPrice: 3500,
    discount: 69,
    category: 'Infection',
    parameters: ['HIV', 'HBsAg', 'HCV', 'VDRL', 'CBC', 'ESR', 'CRP'],
    description: 'Complete infection screening covering HIV, Hepatitis B & C, syphilis, and inflammatory markers. Confidential and accurate results.',
    reportTime: 24,
    isPackage: true,
    includedTests: ['HIV 1&2', 'HBsAg', 'Anti-HCV', 'VDRL', 'CBC', 'ESR', 'CRP'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Gurgaon', 'Jaipur'],
    active: true,
    testsCount: 18,
    preparations: ['No fasting required', 'Collect sample before starting any medication'],
  },
  {
    id: 'smart-plus-full-body',
    name: 'Smart Plus Full Body Checkup',
    price: 1899,
    originalPrice: 4200,
    discount: 54,
    category: 'Full Body',
    parameters: ['Lipid', 'Liver', 'Kidney', 'Thyroid', 'HbA1c', 'Vitamin D', 'Vitamin B12', 'CBC', 'Iron'],
    description: 'Comprehensive health monitoring with 102 parameters covering all vital organs, bone health, and diabetes.',
    reportTime: 12,
    isPackage: true,
    includedTests: ['CBC', 'Lipid Profile', 'Liver Function', 'Kidney Function', 'Thyroid Profile', 'HbA1c', 'Vitamin D', 'Vitamin B12', 'Iron Studies'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai'],
    active: true,
    testsCount: 102,
    preparations: ['10-12 hours fasting required'],
  },
  {
    id: 'women-premium-health',
    name: 'Premium Women Health Checkup',
    price: 2499,
    originalPrice: 6500,
    discount: 61,
    category: 'Women Health',
    parameters: ['Hormone Panel', 'Thyroid', 'Calcium', 'Vitamin D', 'Iron', 'HbA1c', 'Arthritis Screen', 'Cancer Markers'],
    description: 'Specially designed advanced health checkup for women over 30 to track hormones, bone health, and preemptive screenings.',
    reportTime: 15,
    isPackage: true,
    includedTests: ['FSH, LH, Prolactin', 'Thyroid Profile', 'Calcium', 'Vitamin D', 'Vitamin B12', 'Iron Profile', 'HbA1c', 'CBC'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Pune'],
    active: true,
    testsCount: 88,
    preparations: ['10-12 hours fasting required'],
  },
  {
    id: 'senior-wellness',
    name: 'Senior Citizen Complete Wellness',
    price: 3199,
    originalPrice: 8900,
    discount: 64,
    category: 'Full Body',
    parameters: ['Cardiac Markers', 'Bone Health', 'Kidney', 'Liver', 'Arthritis', 'Diabetes', 'Vitamins', 'Urine'],
    description: 'Tailored specifically for the elderly to monitor chronic conditions, bone density markers, and cardiac health.',
    reportTime: 14,
    isPackage: true,
    includedTests: ['Advanced Cardiac Risk Profile', 'KFT', 'LFT', 'HbA1c', 'Bone Health Profile', 'Arthritis Panel', 'Vitamin Panel'],
    cities: ['Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Kolkata'],
    active: true,
    testsCount: 110,
    preparations: ['12 hours fasting required'],
  },
  {
    id: 'kids-health-check',
    name: 'Healthy Kids Checkup (5-15 Yrs)',
    price: 999,
    originalPrice: 2200,
    discount: 54,
    category: 'Full Body',
    parameters: ['CBC', 'Iron', 'Calcium', 'Vitamin D', 'Allergy Screen', 'Thyroid'],
    description: 'Essential growth and development monitoring for children focusing on nutrition, bone health, and common allergies.',
    reportTime: 12,
    isPackage: true,
    includedTests: ['CBC', 'Iron deficiency panel', 'Calcium', 'Vitamin D', 'IgE Total', 'TSH'],
    cities: ['Delhi', 'Noida', 'Gurgaon', 'Mumbai', 'Bangalore'],
    active: true,
    testsCount: 42,
    preparations: ['No special preparation needed'],
  }
];
// Sample slots
export const sampleSlots = [
  { id: 'slot-1', date: '2026-04-11', time: '07:00 AM - 08:00 AM', city: 'Delhi', maxBookings: 5, currentBookings: 2, available: true },
  { id: 'slot-2', date: '2026-04-11', time: '08:00 AM - 09:00 AM', city: 'Delhi', maxBookings: 5, currentBookings: 0, available: true },
  { id: 'slot-3', date: '2026-04-11', time: '09:00 AM - 10:00 AM', city: 'Delhi', maxBookings: 5, currentBookings: 4, available: true },
  { id: 'slot-4', date: '2026-04-11', time: '10:00 AM - 11:00 AM', city: 'Delhi', maxBookings: 5, currentBookings: 5, available: false },
  { id: 'slot-5', date: '2026-04-11', time: '07:00 AM - 08:00 AM', city: 'Mumbai', maxBookings: 5, currentBookings: 1, available: true },
  { id: 'slot-6', date: '2026-04-11', time: '08:00 AM - 09:00 AM', city: 'Mumbai', maxBookings: 5, currentBookings: 0, available: true },
  { id: 'slot-7', date: '2026-04-12', time: '07:00 AM - 08:00 AM', city: 'Delhi', maxBookings: 5, currentBookings: 0, available: true },
  { id: 'slot-8', date: '2026-04-12', time: '08:00 AM - 09:00 AM', city: 'Delhi', maxBookings: 5, currentBookings: 0, available: true },
  { id: 'slot-9', date: '2026-04-12', time: '09:00 AM - 10:00 AM', city: 'Delhi', maxBookings: 5, currentBookings: 0, available: true },
  { id: 'slot-10', date: '2026-04-12', time: '07:00 AM - 08:00 AM', city: 'Bangalore', maxBookings: 5, currentBookings: 0, available: true },
  { id: 'slot-11', date: '2026-04-13', time: '07:00 AM - 08:00 AM', city: 'Delhi', maxBookings: 5, currentBookings: 0, available: true },
  { id: 'slot-12', date: '2026-04-13', time: '08:00 AM - 09:00 AM', city: 'Mumbai', maxBookings: 5, currentBookings: 0, available: true },
];

// Sample bookings for demo
export const sampleBookings: Booking[] = [
  {
    id: 'BK001',
    userId: 'user1',
    items: [{ testId: 'fit-india-essential', testName: 'Fit India Full Body Checkup - Essential', price: 1499 }],
    totalAmount: 1499,
    status: 'completed',
    patientName: 'Rahul Sharma',
    phone: '9876543210',
    email: 'rahul@example.com',
    address: '123, Sector 15, Noida',
    city: 'Noida',
    date: '2026-04-05',
    timeSlot: '07:00 AM - 08:00 AM',
    paymentId: 'pay_mock_001',
    paymentStatus: 'paid',
    phlebotomistName: 'Amit Kumar',
    createdAt: new Date('2026-04-04'),
    updatedAt: new Date('2026-04-06'),
  },
  {
    id: 'BK002',
    userId: 'user1',
    items: [{ testId: 'thyroid-profile', testName: 'Thyroid Profile Total', price: 429 }],
    totalAmount: 429,
    status: 'processing',
    patientName: 'Rahul Sharma',
    phone: '9876543210',
    address: '123, Sector 15, Noida',
    city: 'Noida',
    date: '2026-04-08',
    timeSlot: '08:00 AM - 09:00 AM',
    paymentId: 'pay_mock_002',
    paymentStatus: 'paid',
    createdAt: new Date('2026-04-07'),
    updatedAt: new Date('2026-04-08'),
  },
  {
    id: 'BK003',
    userId: 'user2',
    items: [
      { testId: 'cbc-test', testName: 'Complete Blood Count (CBC) Test', price: 299 },
      { testId: 'blood-sugar-fasting', testName: 'Blood Sugar Fasting', price: 69 },
    ],
    totalAmount: 368,
    status: 'collected',
    patientName: 'Priya Patel',
    phone: '9876543211',
    email: 'priya@example.com',
    address: '45, MG Road, Bangalore',
    city: 'Bangalore',
    date: '2026-04-09',
    timeSlot: '09:00 AM - 10:00 AM',
    paymentId: 'pay_mock_003',
    paymentStatus: 'paid',
    phlebotomistName: 'Suresh R',
    createdAt: new Date('2026-04-08'),
    updatedAt: new Date('2026-04-09'),
  },
  {
    id: 'BK004',
    userId: 'user3',
    items: [{ testId: 'heart-health-advance', testName: 'Heart Health Checkup - Advanced', price: 1299 }],
    totalAmount: 1299,
    status: 'pending',
    patientName: 'Anil Verma',
    phone: '9876543212',
    address: '78, Connaught Place, Delhi',
    city: 'Delhi',
    date: '2026-04-11',
    timeSlot: '07:00 AM - 08:00 AM',
    paymentId: 'pay_mock_004',
    paymentStatus: 'paid',
    createdAt: new Date('2026-04-09'),
    updatedAt: new Date('2026-04-09'),
  },
];

// Sample users for admin
export const sampleUsers: User[] = [
  {
    uid: 'user1',
    name: 'Rahul Sharma',
    email: 'rahul@example.com',
    phone: '9876543210',
    role: 'user',
    familyMembers: [
      { id: 'fm1', name: 'Sneha Sharma', age: 28, gender: 'female', relation: 'Spouse' },
      { id: 'fm2', name: 'Arjun Sharma', age: 5, gender: 'male', relation: 'Son' },
    ],
    city: 'Noida',
    address: '123, Sector 15, Noida',
    createdAt: new Date('2026-01-15'),
  },
  {
    uid: 'user2',
    name: 'Priya Patel',
    email: 'priya@example.com',
    phone: '9876543211',
    role: 'user',
    familyMembers: [],
    city: 'Bangalore',
    address: '45, MG Road, Bangalore',
    createdAt: new Date('2026-02-20'),
  },
  {
    uid: 'user3',
    name: 'Anil Verma',
    email: 'anil@example.com',
    phone: '9876543212',
    role: 'user',
    familyMembers: [
      { id: 'fm3', name: 'Meera Verma', age: 55, gender: 'female', relation: 'Mother' },
    ],
    city: 'Delhi',
    address: '78, Connaught Place, Delhi',
    createdAt: new Date('2026-03-10'),
  },
  {
    uid: 'admin1',
    name: 'Admin User',
    email: 'admin@accuratelabs.com',
    phone: '9999999999',
    role: 'admin',
    familyMembers: [],
    city: 'Delhi',
    createdAt: new Date('2025-12-01'),
  },
];

